trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  resource_group: 'az-104-tfbcknd'
  storage_account: 'az104tfbckndstr'
  container: 'tfbcknd-blb'
  key: 'terraform.tfstate'
  tf_version: '1.13.0'


jobs:
  - job: Infradeployment
    steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: '$(tf_version)'
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'az104-practice'
          backendAzureRmResourceGroupName: '$(resource_group)'
          backendAzureRmStorageAccountName: '$(storage_account)'
          backendAzureRmContainerName: '$(container)'
          backendAzureRmKey: '$(key)'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          backendAzureRmUseEntraIdForAuthentication: true
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'plan'
          environmentServiceNameAzureRM: 'az104-practice'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          commandOptions: '-out=$(System.DefaultWorkingDirectory)/tfplan'
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'apply'
          environmentServiceNameAzureRM: 'az104-practice'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          commandOptions: '$(System.DefaultWorkingDirectory)/tfplan'
