trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: backendconfigs

jobs:
  - job: TerraformInstall
    steps:
      - task: TerraformInstaller@1
        displayName: Install Terraform
        inputs:
          terraformVersion: '1.12.0'
      
      - task: TerraformTaskV4@4
        displayName: Terraform Init
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          backendServiceArm: 'az104-practice'
          backendAzureRmResourceGroupName: $(resource_group)
          backendAzureRmStorageAccountName: $(storage_account)
          backendAzureRmContainerName: $(container)
          backendAzureRmKey: $(key)
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'destroy'
          environmentServiceNameAzureRM: 'az104-practice'