---

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - group: backendconfigs


stages:
  - stage: PlanStage
    jobs:
      - job: TerraformInstall
        steps:
          - task: TerraformInstaller@1
            displayName: Install
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            displayName: Init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendAzureRmUseEntraIdForAuthentication: false
              backendServiceArm: 'az104-practice'
              backendAzureRmResourceGroupName: $(resource_group)
              backendAzureRmStorageAccountName: $(storage_account)
              backendAzureRmContainerName: $(container)
              backendAzureRmKey: $(key)
              backendAzureRmUseCliFlagsForAuthentication: false
          - task: TerraformTask@5
            displayName: Plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: $(System.DefaultWorkingDirectory)
              commandOptions: '-out=$(System.DefaultWorkingDirectory)/tfplan' #Generate tfplan file
              environmentServiceNameAzureRM: 'az104-practice'
          - task: PublishPipelineArtifact@1
            displayName: Publish
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/tfplan' #Publishing only the tfplan binary file
              artifact: 'tfplan'
              publishLocation: 'pipeline'
          
