---

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - group: backendconfigs

stages:
##########################################
###         STAGE 1: PLAN             ###
##########################################
  - stage: PlanStage
    jobs:
      - job: TerraformPlan
        steps:
          - task: TerraformInstaller@1
            displayName: Install
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            displayName: Init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendAzureRmUseEntraIdForAuthentication: false
              backendServiceArm: 'az104-practice'
              backendAzureRmResourceGroupName: $(resource_group)
              backendAzureRmStorageAccountName: $(storage_account)
              backendAzureRmContainerName: $(container)
              backendAzureRmKey: $(key)
              backendAzureRmUseCliFlagsForAuthentication: false
          - task: TerraformTask@5
            displayName: Plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: $(System.DefaultWorkingDirectory)
              commandOptions: '-out=tfplan' #Generate tfplan file
              environmentServiceNameAzureRM: 'az104-practice'

          #Publishing the tfplan file
          - publish: tfplan
            artifact: tfplan

##########################################
###         STAGE 2: APPLY             ###
##########################################
  - stage: ApplyStage
    dependsOn: PlanStage
    condition: succeeded()
    jobs:
      - deployment: ManualApproval # This job name is more descriptive.
        displayName: ManualApproval
        environment: approval-env # This line links the job to the environment and its checks.
        strategy:
          runOnce:
            deploy:
              steps:
                - task: TerraformInstaller@1
                  displayName: Install
                  inputs:
                    terraformVersion: 'latest'
                
                #Downloading the tfplan file
                - download: current
                  artifact: tfplan
                - task: TerraformTask@5
                  displayName: Apply
                  inputs:
                    provider: 'azurerm'
                    command: 'apply'
                    commandOptions: '--auto-approve $(Pipeline.Workspace)/tfplan'
                    environmentServiceNameAzureRM: 'az104-practice'

