trigger: none

pool:
  vmImage: ubuntu-latest
  
variables:
  resourcegroupname: az-104-tfbcknd
  storageaccount: randomazbckndstrge
  container: statecontainer
  key: terraform.tfstate
  serviceconnection: randomtfazspn

jobs:
  - job: Infradeployment
    displayName: Infra deployment thru TF
    steps:
      - task: TerraformInstaller@1
        displayName: InstallTerraform
        inputs:
          terraformVersion: '1.12.0'
      - task: TerraformTask@5
        displayName: "Tf Init"
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'randomtfazspn'
          backendAzureRmResourceGroupName: '$(resourcegroupname)'
          backendAzureRmStorageAccountName: '$(storageaccount)'
          backendAzureRmContainerName: '$(container)'
          backendAzureRmKey: '$(key)'
      - task: TerraformTask@5
        displayName: "Tf Validate"
        inputs:
          provider: 'azurerm'
          command: 'validate'
      - task: DownloadSecureFile@1
        displayName: "Downloading .tfvars"
        inputs:
          secureFile: 'variables.tfvars'
      - task: TerraformTask@5
        displayName: "Tf Plan"
        inputs:
          provider: 'azurerm'
          command: 'plan'
          commandOptions: '-var-file=$(Agent.TempDirectory)/terraform.tfvars -out=tfplan'
          environmentServiceNameAzureRM: 'randomtfazspn'
      - task: TerraformTask@5
        displayName: "Tf Apply"
        inputs:
          provider: 'azurerm'
          command: 'apply'
          commandOptions: 'tfplan'
          environmentServiceNameAzureRM: 'randomtfazspn'





